[package]
name = "tower-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tower = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
